### ISSUE TITLE
How do I make a custom fashion pack?

### ISSUE THREAD

**Issue by PurpleHel** [ArtixAllMighty/JustFashion#1]
I've got all the items for it saved as png files in the right format for skins (Cos I've been using skin maker websites to change clothes.)

**Comment by AbsolemJackdaw** [comment]
its tucked far away for some reason... i'll try to get it back up on the front page

https://github.com/ArtixAllMighty/JustFashion/blob/9fb2f7a0af9dec38620a6dd2ef8029a03491e787/README.md

**Comment by AbsolemJackdaw** [comment]
its back up on the front page

**Comment by PurpleHel** [comment]
Thanks!
