### ISSUE TITLE
fashion-1.16.4-2.4.0.0  modload error

### ISSUE THREAD

**Issue by Daejangnamu** [ArtixAllMighty/JustFashion#13]
Forge 1.16.4-35.1.12

![123123333](https://user-images.githubusercontent.com/52635462/102125179-9ae56300-3e8c-11eb-8074-8ebda080440d.png)

[crash-2020-12-15_04.16.28-fml.txt](https://github.com/ArtixAllMighty/JustFashion/files/5691073/crash-2020-12-15_04.16.28-fml.txt)

**Comment by AbsolemJackdaw** [comment]
https://www.curseforge.com/minecraft/mc-mods/just-fashion?comment=141

https://www.curseforge.com/minecraft/mc-mods/sublib
