### ISSUE TITLE
JustFashion layers do not persist after disconnecting

### ISSUE THREAD

**Issue by Qout2020** [ArtixAllMighty/JustFashion#14]
Hi there!

I primarily use this mod on a communal server with folks and we have MorePlayerModels installed, so I like to set my avatar to Fashion mode and enable masking on all the layers to keep armor off but keep the models on.
Everytime I disconnect or load into a new world however, it seems like all the layer masks turn off again!

Is there any way to set a default that Just Fashion will immediately set on connect/persist after disconnection?  Let me know!

**Comment by Qout2020** [comment]
Ah!!  I realize I should have put this here:
MC Version: 1.12.2
JustFashion version: 1.12.2-0.1.2.0
This is in conjunction with a custom modpack, here are all the mods:
![image](https://user-images.githubusercontent.com/67447124/114082808-322b5780-987c-11eb-88ba-4bc59b0d624d.png)

And this also does not work in singleplayer, either.

**Comment by AbsolemJackdaw** [comment]
That has indeed been an issue in the past, but has been resolved in later versions of the game/mod. 

I don't have a lot of time on my hands these past months / year, and I have never been a fan of backport updates, So it is sad to say that you'll have to live with the missing feature until you update !
