### ISSUE TITLE
[Suggestion] JustFasion more toggable layer.

### ISSUE THREAD

**Issue by Taknax** [ArtixAllMighty/JustFashion#16]
I have wings mod and the layer is toggable. Thats pretty useful.
Is there a way all armor slots gets toggable. Then you could wear your suit under your armor, or does the JustFashion layer replace the armor layer?

**Comment by AbsolemJackdaw** [comment]
Just Fashion replaces armor layers. 
two states are available :
mod : fashion with togglable layers (no armor)
vanilla : armor with all layers active

you could always make a resource pack that contains armor to match what you are wearing 'underneath'

**Comment by Taknax** [comment]
Ok. Gonna try out. Thank you.
