### ISSUE TITLE
Crash in 1.16

### ISSUE THREAD

**Issue by GekidoLukas** [ArtixAllMighty/JustFashion#17]
Crashreport: https://pastebin.com/N3i7bwyv

So I am using a lot of different mods. It most likely is a conflict, but I don't know which ^^"
I hope you will be able to resolve this issue ^^

**Comment by AbsolemJackdaw** [comment]
Caused by 0: java.lang.NoClassDefFoundError: lib/util/networking/IPacketBase

what version are you using ? 
for the last one or two version you dont need sublib anymore, but the ones before you do need it.

**Comment by GekidoLukas** [comment]
I am using the latest 1.16.4 Version: 2.4.0.0.

**Comment by AbsolemJackdaw** [comment]
yeah you need SubLib for that version
