### ISSUE TITLE
"Fashion Mod encountered an error during common_setup event phase"

### ISSUE THREAD

**Issue by tcp-kitty** [ArtixAllMighty/JustFashion#19]
This happens when starting on 1.16.x when starting with the mod, only optifine installed, via MultiMC jarmod feature
Attaching log and crashlog in case
[latest.log](https://github.com/ArtixAllMighty/JustFashion/files/8137130/latest.log)
[crash-2022-02-25_00.04.32-fml.txt](https://github.com/ArtixAllMighty/JustFashion/files/8137132/crash-2022-02-25_00.04.32-fml.txt)

**Comment by AbsolemJackdaw** [comment]
Sublib is needed for 1.16
The dependency has been removed for later versions
