### ISSUE TITLE
[1.14.4] Crash on load with Forge release build. java.lang.NoSuchFieldException: layerRenderers

### ISSUE THREAD

**Issue by ProsperCraft** [ArtixAllMighty/JustFashion#2]
https://gist.github.com/ProsperCraft/6452b755763ac205fd8f7f230008423d

**Comment by AbsolemJackdaw** [comment]
Totally forgot you also need SRG names for obfuscated minecraft 
Will fix this asap

**Comment by AbsolemJackdaw** [comment]
ps : issue reference in commit ->
https://github.com/ArtixAllMighty/JustFashion/commit/4bac4b3577e3e2e54f9be4f6b7a6084b392b1c1a#diff-24f13173695513992cf5b30b2c929308R103
