### ISSUE TITLE
Minecraft 1.16.5 - Forge 36.2.29 - Crashes at startup - Missing IPacketBase

### ISSUE THREAD

**Issue by sor1n** [ArtixAllMighty/JustFashion#20]
Here is the crash log
[crash-2022-03-24_12.34.02-fml.txt](https://github.com/ArtixAllMighty/JustFashion/files/8341460/crash-2022-03-24_12.34.02-fml.txt)

Forge might have changed the name of the file?

**Comment by AbsolemJackdaw** [comment]
SubLib was still required for that version =) 

https://www.curseforge.com/minecraft/mc-mods/sublib
