### ISSUE TITLE
Incompatibility with Oculus

### ISSUE THREAD

**Issue by oOBoomberOo** [ArtixAllMighty/JustFashion#22]
> [Oculus](https://modrinth.com/mod/oculus) is a shader rendering mod similar to Fabric's Iris or Optifine

Mod Info:
- Just Fashion `1.18.2-4.0.0.1`
- Oculus `1.18.2-1.2.5a`
- Rubidium `0.5.4`

Shader pack: KUDA Shaders v6.1 is used in the screenshot, but any of them will do.

When Showing Fashion is enabled while using a shader, it causes the water render layer to be fixed to the camera's direction.

![image](https://user-images.githubusercontent.com/26600816/201454794-9d57faa6-e3f0-4dbf-8bc2-acf9d8e15378.png)
![image](https://user-images.githubusercontent.com/26600816/201454796-47cd2a6d-c466-46d4-8036-4403086cf5b7.png)

This weird rendering glitch only occurs when you have the hotbar visible. The water renders normally when I hide it with F1.

![2022-11-12_12 45 45](https://user-images.githubusercontent.com/26600816/201454863-3ad52561-800b-4b36-abc6-a3748a23b90e.png)
![2022-11-12_12 45 50](https://user-images.githubusercontent.com/26600816/201454864-5ce9d657-5053-4d89-b407-50cff1ab6b82.png)

**Comment by AbsolemJackdaw** [comment]
I have pushed a fix, this should solve the issue
https://www.curseforge.com/minecraft/mc-mods/just-fashion/files/4082981
could you try it out and report to me if it works again ?

**Comment by oOBoomberOo** [comment]
Yep, that fixed it. Would you be willing to publish the same fix for 1.18.2? But if not, would you mind if I patch it myself and use it on my server?

**Comment by AbsolemJackdaw** [comment]
This is an easy fix, I'll see what 1.18.2 version I have lying around and try to apply the patch to it when I find five minutes of free time

**Comment by AbsolemJackdaw** [comment]
I just went trough my code and i seem only to have 1.18 in copy and not 1.18.2.
I applied a quick 1.18.2 update to it, and applied the key fix that came with 4.0.0.1, and added the rendering fix. 
no guarantees at this point, as it is a fix I slapped quickly together

file is uploaded, feel free to use !
