### ISSUE TITLE
[1.14.4] Sidendness issues when load on the client, loads fine on the server - this is a first :)

### ISSUE THREAD

**Issue by ProsperCraft** [ArtixAllMighty/JustFashion#3]
![Fashion](https://user-images.githubusercontent.com/4427684/65005669-d7a76080-d8bd-11e9-9afc-c63ebdfcd1c3.png)

Latest Log-
https://gist.github.com/ProsperCraft/515bd659e518f117aff9f2e84755245d

JustFashion-1.14.4-2.1.0.1.jar

**Comment by AbsolemJackdaw** [comment]
```
com.google.gson.JsonParseException:  
 com.google.gson.stream.MalformedJsonException:   
Unterminated object at line 5 column 10 path $.pack.pack_format

```

check your json file

**Comment by AbsolemJackdaw** [comment]
i also think this is unrelated to my json files

**Comment by AbsolemJackdaw** [comment]
oh wait
``` 
java.lang.NoClassDefFoundError: lib/modelloader/ModelHandle

```

dont forget sublib

**Comment by AbsolemJackdaw** [comment]
Closing the issue : with no answer after a month on a suggested fix, I'll be assuming you managed to fix it and didn't bother to come back and tell it was indeed this.
