### ISSUE TITLE
Suggestion: being able to open/CLOSE Wardrobe GUI with the same button

### ISSUE THREAD

**Issue by sepsol** [ArtixAllMighty/JustFashion#6]
(As other GUIs like Inventory)

**Comment by AbsolemJackdaw** [comment]
thats already the case.

https://github.com/ArtixAllMighty/JustFashion/blob/master/src/main/java/subaraki/fashion/screen/WardrobeScreen.java#L200-L209

just noticed i _may_ have hardcoded that in though

**Comment by AbsolemJackdaw** [comment]
I'll see what I can do !

**Comment by sepsol** [comment]
Thank you :)

**Comment by AbsolemJackdaw** [comment]
76c0976d37c0e8a1703a76c7b7adcae79cf90d93
