### ISSUE TITLE
JEI menu shouldn't pop up when in Wardrobe GUI (it shouldn't behave like inventory)

### ISSUE THREAD

**Issue by sepsol** [ArtixAllMighty/JustFashion#7]
It makes the surrounding so messy.

**Comment by AbsolemJackdaw** [comment]
got an image ?
Also, I dont think i can prevent JEI from popping up ?

**Comment by sepsol** [comment]
Here's an image:

![image](https://user-images.githubusercontent.com/47871887/67718053-3a733800-f9e4-11e9-9346-e12fe327b3b8.png)


- Minecraft 1.14.4
- Forge 28.1.70
- OptiFine HD U F4
- Just Fashion 2.1.0.2
- JEI 6.0.0.18

Also there are other mods that add GUIs like [WorldHandler ](https://www.curseforge.com/minecraft/mc-mods/world-handler-command-gui)which don't cause JEI to open (and close with the same button that opens it), so I think it might be possible. JEI doesn't allow the four dots on the left (outside the main box) to be used at all!

**Comment by AbsolemJackdaw** [comment]
Ill look into it

**Comment by AbsolemJackdaw** [comment]
There is a rewrite necesairy for this. I am not ready for that rewrite.
Temporary fox : use _ctrl + o_ to hide JEI when in the wardrobe

**Comment by sepsol** [comment]
Thanks, I'll do this for the time-being. Can you add a temporary quick fix which presses JEI hide button after the wardrobe button is pressed, and when closing the wardrobe, presses the JEI show button before closing it, all automatically?! Is this even possible?!!
